import { getPuzzleSource, hasConcretePuzzlePayload, parseTrustedPuzzleUrl } from './puzzle-url.mjs';
import { buildPuzzleToolLinks } from './puzzle-tool-links.mjs';

const seedPuzzles = [
  { number: 128, title: 'Thermometer', type: '逻辑题', author: 'Mina K.', tags: ['Thermometer', 'Example Puzzle'], ratings: [3.4, 2.1, 4.8], votes: 18, completed: false, source: 'puzz.link', url: 'https://puzz.link/', note: '一组温度计交错在网格中。填满它们时，注意每支温度计的方向。', rules: '每支温度计必须从球形端开始连续填满，直到边界或另一支温度计。', inputMode: 'external' },
  { number: 127, title: 'Five Cells', type: '逻辑题', author: 'Yusuke', tags: ['Five Cells'], ratings: [3.7, 3.5, 4.6], votes: 26, completed: true, source: 'puzz.link', url: 'https://puzz.link/', note: '每一块区域都恰好包含五个格子。相邻区域的边界会告诉你下一步。', rules: '将盘面分成每块五格的区域，线条不得形成面积不符的闭合区域。', inputMode: 'external' },
  { number: 126, title: 'Wordoku No. 03', type: '文字题', author: 'Katherine L.', tags: ['Wordoku'], ratings: [2.2, 3.8, 4.2], votes: 12, completed: false, source: 'penpa+', url: 'https://swaroopg92.github.io/penpa-edit/', note: '字母替代数字的经典数独变体，词语会给出额外线索。', rules: '每行、每列和每个宫内都不得重复字母。', inputMode: 'external' },
  { number: 125, title: 'The Wrong Puzzle', type: '逻辑题', author: 'Lumen', tags: ['Wrong Puzzle', 'Meta'], ratings: [4.6, 4.3, 4.5], votes: 31, completed: true, source: '填空题', url: '', note: '这是一个故意写错的谜题。先找到规则中的不一致，再开始解题。', rules: '找出题面中的矛盾，并在答案框写下导致矛盾的规则。', inputMode: 'blank', answer: '规则 3' },
  { number: 124, title: 'Arrow Maze', type: '逻辑题', author: 'Mori', tags: ['Arrow Maze', 'Example Puzzle'], ratings: [3.1, 2.8, 4.1], votes: 9, completed: false, source: 'puzz.link', url: 'https://puzz.link/', note: '沿箭头方向走过每个格子，每一步都会缩小下一步的选择。', rules: '从起点出发，遵守箭头方向访问全部格子且不重复。', inputMode: 'external' },
  { number: 123, title: 'Regional Sudoku', type: '逻辑题', author: 'Aster', tags: ['Sudoku'], ratings: [3.9, 3.2, 4.7], votes: 22, completed: true, source: 'puzz.link', url: 'https://puzz.link/', note: '区域边界会在标准数独之外制造新的关系。', rules: '每行、每列和每个不规则区域都填入 1 至 9。', inputMode: 'external' },
  { number: 122, title: 'Kakuro Evening', type: '逻辑题', author: 'Mina K.', tags: ['Kakuro'], ratings: [2.8, 2.3, 4.0], votes: 7, completed: false, source: 'puzz.link', url: 'https://puzz.link/', note: '适合周末晚上慢慢完成的一题。', rules: '每段数字不得重复，并满足左上角的和。', inputMode: 'external' },
  { number: 121, title: 'Letter Loop', type: '文字题', author: 'Yusuke', tags: ['Word', 'Example Puzzle'], ratings: [3.5, 3.6, 4.4], votes: 15, completed: false, source: '填空题', url: '', note: '将字母线索串成一个没有断点的循环。', rules: '根据线索填入一个闭合的字母序列。', inputMode: 'blank', answer: 'ARCHIVE' }
];

const state = {
  puzzles: JSON.parse(localStorage.getItem('puzarchive-puzzles') || 'null') || seedPuzzles,
  folders: JSON.parse(localStorage.getItem('puzarchive-folders') || 'null') || [
    { id: 'india', name: 'Logic Masters India', count: 38, parent: null },
    { id: 'japan', name: '日本パズル協会', count: 24, parent: null },
    { id: 'personal', name: '个人收藏', count: 17, parent: null }
  ],
  visible: 6,
  sort: 'recent',
  filter: 'all',
  filePath: ['全部文件'],
  collections: [],
  api: false
};
const app = document.querySelector('#app');
const modalBackdrop = document.querySelector('#modalBackdrop');
const modalContent = document.querySelector('#modalContent');
const toastElement = document.querySelector('#toast');
let toastTimer;

function saveState() { if (!state.api) { localStorage.setItem('puzarchive-puzzles', JSON.stringify(state.puzzles)); localStorage.setItem('puzarchive-folders', JSON.stringify(state.folders)); } }
async function apiRequest(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error((await response.json()).error || `HTTP ${response.status}`); return response.json(); }
function applyPuzzleData(puzzles) { state.puzzles = puzzles.map((puzzle) => ({ ...puzzle, ratings: puzzle.ratings.map(Number), userRating: puzzle.userRating || null, votes: Number(puzzle.votes) })); }
async function bootstrapDatabase() { try { const [puzzleData, folderData, collectionData] = await Promise.all([apiRequest('/api/puzzles'), apiRequest('/api/folders'), apiRequest('/api/collections')]); applyPuzzleData(puzzleData.puzzles); state.folders = folderData.folders.map((folder) => ({ id: String(folder.id), name: folder.name, count: folder.count, parent: folder.parent })); state.collections = collectionData.collections; state.api = true; renderRoute(); showToast('已连接 SQLite 数据库'); } catch { /* Static file servers intentionally use the local demo fallback. */ } }
function esc(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
function ratingMarkup(values, votes) { return `<div class="rating-set" title="${votes} 位解题者的平均评分"><span class="rating-item">✎ <b>${values[0].toFixed(1)}</b></span><span class="rating-item">♧ <b>${values[1].toFixed(1)}</b></span><span class="rating-item">♥ <b>${values[2].toFixed(1)}</b></span></div>`; }
function tagMarkup(tags) { return `<div class="tag-list">${tags.map((tag) => `<span class="tag ${tag === 'Wrong Puzzle' ? 'warning' : tag === 'Example Puzzle' ? 'type' : ''}">${esc(tag)}</span>`).join('')}</div>`; }
function showToast(message) { toastElement.textContent = message; toastElement.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toastElement.classList.remove('show'), 2600); }
function openModal(content) { modalContent.innerHTML = content; modalBackdrop.hidden = false; document.body.style.overflow = 'hidden'; }
function closeModal() { modalBackdrop.hidden = true; document.body.style.overflow = ''; }
function button(text, id = '', className = 'button button-dark') { return `<button class="${className}" type="button"${id ? ` id="${id}"` : ''}>${text}</button>`; }

function getRoute() { const hash = window.location.hash.slice(1) || 'home'; const puzzleMatch = hash.match(/^puzzle-(\d+)$/); const collectionMatch = hash.match(/^collection-(\d+)$/); if (puzzleMatch) return { name: 'puzzle', number: Number(puzzleMatch[1]) }; if (collectionMatch) return { name: 'collection', id: Number(collectionMatch[1]) }; return { name: hash.split('/')[0] || 'home' }; }
function setBreadcrumb(name) { const labels = { home: '首页', library: '题库', collections: '题集列表', collection: '题集', files: '文件管理', records: '我的记录', authors: '作者', puzzle: '题目' }; document.querySelector('#breadcrumbCurrent').textContent = labels[name] || '首页'; const activeRoute = ['puzzle', 'collection'].includes(name) ? (name === 'collection' ? 'collections' : 'library') : name; document.querySelectorAll('[data-route-link]').forEach((link) => link.classList.toggle('active', link.dataset.routeLink === activeRoute)); }

function filteredPuzzles() {
  const filtered = state.puzzles.filter((puzzle) => { if (state.filter === 'completed') return puzzle.completed; if (state.filter === 'wrong') return puzzle.tags.includes('Wrong Puzzle'); if (state.filter === 'logic') return puzzle.type === '逻辑题'; if (state.filter === 'word') return puzzle.type === '文字题'; return true; });
  return [...filtered].sort((a, b) => state.sort === 'rating' ? b.ratings[2] - a.ratings[2] : b.number - a.number);
}

function renderLibrary() {
  const items = filteredPuzzles().slice(0, state.visible);
  const completed = state.puzzles.filter((puzzle) => puzzle.completed).length;
  return `<div class="page-wrap-inner"><section class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span>PUZZLE LIBRARY</p><h1 id="page-title">题库<span class="heading-period">.</span></h1></div>${button('<span class="button-plus">+</span>添加题目', 'addPuzzleButton')}</section><section class="notice-strip" aria-label="公告"><div class="notice-symbol">✦</div><div class="notice-copy"><span class="notice-kicker">公告 · OCT 2026</span><strong>秋季谜题交换开始了</strong><span>提交你的原创题目，和朋友交换一场解题。</span></div><button class="text-button" type="button" id="noticeButton">查看公告 <span>→</span></button></section><section class="overview-grid" aria-label="题库概览"><div class="stat-block"><span class="stat-label">全部题目</span><strong>128</strong><span class="stat-meta positive">↑ 12 <em>本月新增</em></span></div><div class="stat-block"><span class="stat-label">已完成</span><strong>${completed}</strong><span class="stat-meta"><span class="mini-bar"><i style="width: ${Math.round(completed / state.puzzles.length * 100)}%"></i></span>${Math.round(completed / state.puzzles.length * 100)}% of demo library</span></div><div class="stat-block stat-block-wide"><span class="stat-label">评分机制</span><div class="activity-line"><span class="rating-legend">✎ 逻辑难度　♧ 通灵难度　♥ 喜爱程度</span></div></div></section><section class="library-section" id="library"><div class="section-heading"><div class="section-title-group"><h2>所有题目</h2><span class="count-badge">128</span></div><div class="view-controls"><div class="segmented-control" role="tablist" aria-label="题目排序"><button class="segment ${state.sort === 'recent' ? 'active' : ''}" type="button" data-sort="recent">最近添加</button><button class="segment ${state.sort === 'number' ? 'active' : ''}" type="button" data-sort="number">题号</button><button class="segment ${state.sort === 'rating' ? 'active' : ''}" type="button" data-sort="rating">评分</button></div><button class="icon-button bordered" type="button" title="筛选" aria-label="筛选" id="filterButton">☷</button></div></div><div class="filter-row" id="filterRow" ${state.filter === 'all' ? 'hidden' : ''}><span class="filter-caption">FILTER BY</span>${[['all', '全部'], ['logic', '逻辑题'], ['word', '文字题'], ['completed', '已完成'], ['wrong', 'Wrong Puzzle']].map(([value, label]) => `<button class="filter-pill ${state.filter === value ? 'active' : ''}" data-filter="${value}" type="button">${label}</button>`).join('')}</div><div class="puzzle-table" role="table" aria-label="谜题列表"><div class="table-head" role="row"><span class="cell-number">NO.</span><span class="cell-puzzle">PUZZLE</span><span class="cell-author">AUTHOR</span><span class="cell-tags">TAGS</span><span class="cell-rating">AVERAGE RATING</span><span class="cell-action"></span></div><div id="puzzleRows">${items.map(renderPuzzleRow).join('')}</div></div><div class="table-footer"><span>显示 <strong>${items.length}</strong> / 128 道题目</span><button class="text-button" type="button" id="loadMoreButton">加载更多 <span>↓</span></button></div></section></div>`;
}

function renderPuzzleRow(puzzle) { return `<div class="puzzle-row ${puzzle.completed ? 'completed' : ''}" role="row"><span class="cell-number" role="cell">#${puzzle.number}</span><div class="puzzle-main" role="cell"><a class="puzzle-title" href="#puzzle-${puzzle.number}">${esc(puzzle.title)}</a><span class="puzzle-subtitle">${esc(puzzle.type)} · ${esc(puzzle.source)}</span></div><span class="cell-author" role="cell"><a class="author-link" href="#authors">${esc(puzzle.author)}</a></span><span class="cell-tags" role="cell">${tagMarkup(puzzle.tags)}</span><span class="cell-rating" role="cell">${ratingMarkup(puzzle.ratings, puzzle.votes)}</span><a class="row-action" title="打开详情" aria-label="打开 ${esc(puzzle.title)}" href="#puzzle-${puzzle.number}">›</a></div>`; }


function renderFiles() { const folders = state.folders; return `<div class="page-wrap-inner"><section class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span>FILE MANAGER</p><h1>文件管理<span class="heading-period">.</span></h1><p class="page-description">把来源、年份和题集放进清晰的文件夹。</p></div>${button('<span class="button-plus">+</span>新建文件夹', 'newFolderButton')}</section><section class="file-toolbar"><div class="file-breadcrumb"><button type="button" data-file-home>全部文件</button>${state.filePath.slice(1).map((part) => `<span> / </span><strong>${esc(part)}</strong>`).join('')}</div><div class="file-actions"><button class="button button-light" type="button" id="sortFilesButton">按最近更新</button><button class="icon-button bordered" type="button" title="列表视图">☷</button></div></section><section class="file-layout"><div class="file-main"><div class="file-section-heading"><span>FOLDERS</span><span>${folders.length} 个文件夹</span></div><div class="folder-cards">${folders.map((folder) => `<button class="folder-card" type="button" data-folder="${esc(folder.id)}"><span class="folder-card-icon">▰</span><strong>${esc(folder.name)}</strong><small>${folder.count} puzzles <span>→</span></small></button>`).join('')}<button class="folder-card folder-card-new" type="button" id="newFolderCard"><span>+</span><strong>新建文件夹</strong></button></div><div class="file-section-heading file-section-heading-spaced"><span>RECENT FILES</span><span>按最近修改</span></div><div class="file-table"><div class="file-row file-head"><span>名称</span><span>位置</span><span>题目</span><span>更新</span></div>${[['Spring Selection', 'Logic Masters India / 2026', '08', '今天'], ['Paper & Pencil / Vol. 01', '日本パズル協会 / 2025', '24', '2 天前'], ['Example Puzzles', '个人收藏 / 2024', '12', '上周']].map(([name, location, count, updated]) => `<a class="file-row" href="#puzzle-128"><span class="file-name"><span class="file-mini-icon">▰</span><strong>${name}</strong></span><span class="muted">${location}</span><span>${count}</span><span class="muted">${updated}</span></a>`).join('')}</div></div><aside class="file-aside"><div class="file-aside-icon">⌘</div><h2>你的题目，<br /><em>有自己的位置。</em></h2><p>用来源、年份和题集整理资料。文件夹可以无限嵌套，之后也能随时移动。</p><div class="tree-mini"><span>⌄　▰ Logic Masters India</span><span>　⌄　▰ 2026</span><span>　　 ›　▰ Spring Selection</span></div></aside></section></div>`; }

function renderRecords() { const completed = state.puzzles.filter((puzzle) => puzzle.completed); return `<div class="page-wrap-inner"><section class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span>PERSONAL LOG</p><h1>我的记录<span class="heading-period">.</span></h1><p class="page-description">这里保存你完成过的题目和评分。</p></div></section><section class="record-summary"><div><span>已完成</span><strong>${completed.length}</strong></div><div><span>已评分</span><strong>0</strong></div><div><span>平均喜爱程度</span><strong>—</strong></div></section><section class="record-list"><div class="file-section-heading"><span>COMPLETED PUZZLES</span><span>${completed.length} 条记录</span></div>${completed.length ? completed.map((puzzle) => `<a class="record-row" href="#puzzle-${puzzle.number}"><span class="record-check">✓</span><span><strong>${puzzle.title}</strong><small>#${puzzle.number} · ${puzzle.author}</small></span><span class="muted">查看题目 →</span></a>`).join('') : '<div class="empty-state">还没有完成的题目。去题库挑一道开始吧。</div>'}</section></div>`; }
function renderAuthors() { const authors = [...new Set(state.puzzles.map((puzzle) => puzzle.author))]; return `<div class="page-wrap-inner"><section class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span>CREATORS</p><h1>作者<span class="heading-period">.</span></h1><p class="page-description">按照作者浏览他们命制的所有题目。</p></div></section><div class="author-grid">${authors.map((author, index) => { const authored = state.puzzles.filter((puzzle) => puzzle.author === author); return `<a href="#library" class="author-card"><span class="author-card-avatar avatar-${['coral', 'mint', 'navy', 'amber'][index % 4]}">${author[0]}</span><strong>${author}</strong><small>${authored.length} 道题目</small><span>查看题目 →</span></a>`; }).join('')}</div></div>`; }

function openPuzzle(number) { window.location.hash = `#puzzle-${number}`; }
function renderPuzzlePage(number) { const puzzle = state.puzzles.find((item) => item.number === number); if (!puzzle) { window.location.hash = '#library'; return ''; } const hasRating = puzzle.userRating; return `<div class="page-wrap-inner puzzle-page"><a class="back-link" href="#library">← 返回题库</a><section class="puzzle-header"><div><p class="eyebrow"><span class="eyebrow-line"></span>PUZZLE #${puzzle.number}</p><h1>${esc(puzzle.title)}<span class="heading-period">.</span></h1><p class="puzzle-meta-large">${esc(puzzle.type)}　·　由 <a href="#authors">${esc(puzzle.author)}</a> 发布　·　${puzzle.votes} 位解题者评分</p></div><div class="puzzle-header-tags">${tagMarkup(puzzle.tags)}<button class="tag-add-button" type="button" id="addTagButton">+ 添加标签</button></div></section><section class="puzzle-content-grid"><div class="puzzle-board-column"><div class="embed-toolbar"><span class="embed-label">${puzzle.inputMode === 'blank' ? 'SELF-CONTAINED' : 'OPEN PUZZLE'}</span></div><div class="puzzle-embed" id="puzzleEmbed">${renderEmbed(puzzle)}</div><div class="puzzle-open-actions">${puzzle.inputMode === 'blank' ? '<span class="muted">这是一个内置填空题</span>' : '<span class="muted">外部题目通过上方工具按钮在新标签页打开</span>'}</div></div><aside class="puzzle-sidebar"><div class="detail-block"><h3>作者的话</h3><p>${esc(puzzle.note)}</p></div><div class="detail-block"><h3>规则</h3><details><summary>查看题目规则</summary><p>${esc(puzzle.rules)}</p><a class="small-link" href="#puzzle-${puzzle.number}">Example Puzzle 题目 ↗</a></details></div><div class="detail-block record-panel"><h3>ANSWER RECORD</h3><p class="record-help">完成题目后，分别评价逻辑难度、通灵难度和喜爱程度。</p><button class="button ${puzzle.completed ? 'button-dark' : 'button-light'}" id="completePuzzleButton" type="button">${puzzle.completed ? '✓ 已完成 · 修改评分' : '标记为已完成'}</button>${hasRating ? `<div class="submitted-rating"><span>我的评分</span>${ratingMarkup(puzzle.userRating, 1)}</div>` : ''}</div><div class="detail-block"><h3>留言板</h3><p class="muted">还没有留言。</p><div class="comment-box"><input type="text" placeholder="写下你的想法" aria-label="留言内容" /><button type="button" id="commentButton">发送</button></div></div></aside></section></div>`; }

function renderPuzzleOpenTools(puzzle) {
  const links = buildPuzzleToolLinks(puzzle.url);
  const trustedUrl = parseTrustedPuzzleUrl(puzzle.url);
  if (!links.length || !trustedUrl) {
    return `<div class="tool-launch-panel tool-launch-blocked" role="alert"><span class="tool-launch-kicker">BLOCKED</span><strong>该链接不在支持的工具范围内</strong><p>请使用 puzz.link、pzv3、pzprxs、pzplus 或 Penpa 系列的官方题目链接。</p></div>`;
  }
  const toolbar = `<div class="solver-toolbar"><div class="solver-toolbar-copy"><span class="tool-launch-kicker">IN-PAGE SOLVER</span><strong>页内解题</strong></div><div class="tool-link-list">${links.map((link) => `<a class="tool-link-button" href="${esc(link.url)}" target="_blank" rel="noopener noreferrer"><span>${esc(link.name)}</span><strong>在新标签页解题 ↗</strong></a>`).join('')}</div></div>`;
  if (!hasConcretePuzzlePayload(trustedUrl.href)) {
    return `<div class="solver-shell">${toolbar}<div class="solver-empty"><strong>这个示例还没有具体题面 URL</strong><p>为避免加载网站首页文本，页内模块已停用。请使用上方工具按钮打开。</p></div></div>`;
  }
  return `<div class="solver-shell">${toolbar}<div class="solver-frame"><iframe src="${esc(trustedUrl.href)}" title="${esc(puzzle.title)}"></iframe></div><p class="solver-note">上方按钮会打开对应网站；当前模块直接在页面内加载原题。</p></div>`;
}

function renderEmbed(puzzle) {
  if (puzzle.inputMode === 'blank') return `<div class="blank-puzzle"><span class="blank-kicker">FILL IN</span><h2>${esc(puzzle.title)}</h2><p>请根据规则填写答案。</p><label><span>你的答案</span><input id="blankAnswer" type="text" placeholder="输入答案" /></label><button type="button" class="button button-dark" id="checkBlankButton">检查答案</button><p id="blankResult" class="blank-result"></p></div>`;
  return renderPuzzleOpenTools(puzzle);
}

function isSupportedPuzzleUrl(value) { return parseTrustedPuzzleUrl(value) !== null; }

function bindPuzzle(number) {
  const puzzle = state.puzzles.find((item) => item.number === number);
  document.querySelector('#completePuzzleButton')?.addEventListener('click', () => openRating(number));
  document.querySelector('#addTagButton')?.addEventListener('click', () => openTagEditor(number));
  bindBlank(puzzle);
  document.querySelector('#commentButton')?.addEventListener('click', () => showToast('留言功能将在账户系统接入后启用'));
}
function openTagEditor(number) { openModal(`<p class="modal-eyebrow">PUZZLE TAGS</p><h2 id="modalTitle">添加标签</h2><p class="modal-intro">标签用于题库筛选；题型标签和 Wrong Puzzle、Example Puzzle 等状态标签可以同时存在。</p><label class="form-field"><span>标签名称</span><input id="newTagName" type="text" placeholder="例如：Sudoku" /></label><div class="modal-footer"><button class="button button-light modal-cancel" type="button">取消</button>${button('保存标签', 'saveTagButton')}</div>`); document.querySelector('#saveTagButton').addEventListener('click', async () => { const tag = document.querySelector('#newTagName').value.trim(); if (!tag) { showToast('请填写标签名称'); return; } try { if (state.api) { const data = await apiRequest(`/api/puzzles/${number}/tags`, { method: 'POST', body: JSON.stringify({ tag }) }); applyPuzzleData(data.puzzles); } else { const puzzle = state.puzzles.find((item) => item.number === number); if (!puzzle.tags.includes(tag)) puzzle.tags.push(tag); saveState(); } closeModal(); renderRoute(); showToast('标签已保存'); } catch (error) { showToast(error.message); } }); }
function bindBlank(puzzle) { document.querySelector('#checkBlankButton')?.addEventListener('click', () => { const answer = document.querySelector('#blankAnswer').value.trim().toLowerCase(); const expected = String(puzzle.answer || '').toLowerCase(); const result = document.querySelector('#blankResult'); if (!answer) { result.textContent = '请填写答案。'; result.className = 'blank-result error'; } else if (expected && answer === expected) { result.textContent = '答案正确，可以提交完成记录。'; result.className = 'blank-result success'; } else { result.textContent = expected ? '还不正确，再试一次。' : '答案已记录，点击完成后进行评分。'; result.className = 'blank-result'; } }); }

function renderHome() { return `<div class="page-wrap-inner home-page"><section class="workspace-header"><div><p class="eyebrow"><span class="eyebrow-line"></span>PUZZLE ARCHIVE</p><h1>工作台<span class="heading-period">.</span></h1><p class="page-description">从公告开始，进入题库、题集和索引。</p></div></section><section class="home-notice-board"><div class="notice-strip" aria-label="公告"><div class="notice-symbol">✦</div><div class="notice-copy"><span class="notice-kicker">公告 · OCT 2026</span><strong>秋季谜题交换开始了</strong><span>提交你的原创题目，和朋友交换一场解题。</span></div><button class="text-button" type="button" id="noticeButton">查看公告 <span>→</span></button></div><div class="notice-strip notice-strip-secondary"><div class="notice-symbol">◎</div><div class="notice-copy"><span class="notice-kicker">最近更新 · OCT 2026</span><strong>题库新增 12 道题目</strong><span>包括来自 PuzArchive 社区的 4 道 Example Puzzle。</span></div><a class="text-button" href="#library">进入题库 <span>→</span></a></div></section><section class="home-links"><a href="#library" class="home-link-card"><span class="home-link-icon">▤</span><span><small>EXPLORE</small><strong>题库</strong><em>128 道题目 →</em></span></a><a href="#collections" class="home-link-card"><span class="home-link-icon">▥</span><span><small>CURATED</small><strong>题集列表</strong><em>04 个题集 →</em></span></a><a href="#files" class="home-link-card"><span class="home-link-icon">⌘</span><span><small>ORGANIZE</small><strong>索引与文件</strong><em>按来源与年份浏览 →</em></span></a></section></div>`; }

function renderCollections() { const collections = state.collections.length ? state.collections : [{ id: 1, name: "New Year's Puzzle Exchange", description: '来自 6 位作者的交换题目，适合周末集中完成。', source: 'PuzArchive community', year: 2026, puzzle_count: 18 }, { id: 2, name: 'Paper & Pencil / Vol. 01', description: '纸笔谜题的第一册精选。', source: '日本パズル協会', year: 2025, puzzle_count: 24 }]; return `<div class="page-wrap-inner"><section class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span>CURATED SETS</p><h1>题集列表<span class="heading-period">.</span></h1><p class="page-description">按主题、比赛和编辑精选浏览一组题目。</p></div>${button('<span class="button-plus">+</span>新建题集', 'newCollectionButton')}</section><section class="collection-directory collection-directory-first"><div class="section-heading compact"><div class="section-title-group"><h2>全部题集</h2><span class="count-badge">${String(collections.length).padStart(2, '0')}</span></div><span class="mono muted">DATABASE COLLECTIONS</span></div><div class="collection-list">${collections.map((collection) => `<a class="collection-row collection-row-large" href="#collection-${collection.id}"><span class="collection-cover ${collection.id % 2 ? 'cover-green' : 'cover-red'}">${collection.id % 2 ? 'N°' : 'PB'}<span>${collection.year || 'SET'}</span></span><span class="collection-info"><strong>${esc(collection.name)}</strong><small>${Number(collection.puzzle_count || 0)} puzzles · ${collection.year || '未定年份'} · ${esc(collection.source || '未注明来源')}</small><em>${esc(collection.description || '')}</em></span><span class="collection-arrow">↗</span></a>`).join('')}</div></section></div>`; }

function renderCollectionPage(id) { const collection = state.currentCollection && Number(state.currentCollection.id) === Number(id) ? state.currentCollection : state.collections.find((item) => Number(item.id) === Number(id)); if (!collection) return `<div class="page-wrap-inner"><div class="empty-state">正在加载题集……</div></div>`; const puzzles = collection.puzzles || []; return `<div class="page-wrap-inner collection-page"><a class="back-link" href="#collections">← 返回题集列表</a><section class="collection-detail-header"><div><p class="eyebrow"><span class="eyebrow-line"></span>COLLECTION · ${collection.year || '—'}</p><h1>${esc(collection.name)}<span class="heading-period">.</span></h1><p class="page-description">${esc(collection.description || '')}</p><p class="collection-detail-meta">${esc(collection.source || '未注明来源')}　·　${puzzles.length} 道题目</p></div><span class="collection-detail-mark">${collection.year ? String(collection.year).slice(-2) : 'SET'}</span></section><section class="collection-detail-grid"><div><div class="section-heading compact"><div class="section-title-group"><h2>题目</h2><span class="count-badge">${String(puzzles.length).padStart(2, '0')}</span></div><span class="mono muted">ORDERED BY COLLECTION</span></div><div class="collection-puzzle-list">${puzzles.map((puzzle, index) => `<a class="collection-puzzle-row" href="#puzzle-${puzzle.number}"><span class="collection-puzzle-number">${String(index + 1).padStart(2, '0')}</span><span><strong>${esc(puzzle.title)}</strong><small>${esc(puzzle.type)} · ${esc(puzzle.author)}</small></span><span class="collection-puzzle-status">${puzzle.completed ? '✓ 已完成' : '未完成'}　→</span></a>`).join('') || '<div class="empty-state">题集暂时没有题目。</div>'}</div></div><aside class="collection-materials"><span class="materials-kicker">REFERENCE MATERIALS</span><h2>资料</h2>${[['IB', collection.ib], ['PB', collection.pb], ['SB', collection.sb]].map(([label, value]) => `<div class="material-row"><span>${label}</span><strong>${esc(value || '尚未添加')}</strong><button type="button" title="打开资料">↗</button>`).join('')}</aside></section></div>`; }

async function loadCollection(id) { if (!state.api) return; try { const data = await apiRequest(`/api/collections/${id}`); state.currentCollection = data.collection; renderRoute(); } catch (error) { showToast(error.message); } }
function bindCollectionList() { document.querySelector('#newCollectionButton')?.addEventListener('click', () => showToast('题集创建表单将在下一阶段接入')); document.querySelectorAll('a[href^="#collection-"]').forEach((link) => link.addEventListener('click', () => { const id = Number(link.getAttribute('href').split('-')[1]); state.currentCollection = null; loadCollection(id); })); }
function renderRoute() { const route = getRoute(); setBreadcrumb(route.name); app.innerHTML = route.name === 'home' ? renderHome() : route.name === 'library' ? renderLibrary() : route.name === 'collections' ? renderCollections() : route.name === 'collection' ? renderCollectionPage(route.id) : route.name === 'files' ? renderFiles() : route.name === 'records' ? renderRecords() : route.name === 'authors' ? renderAuthors() : route.name === 'puzzle' ? renderPuzzlePage(route.number) : renderHome(); if (route.name === 'library') bindLibrary(); if (route.name === 'collections') bindCollectionList(); if (route.name === 'collection' && !state.currentCollection) loadCollection(route.id); if (route.name === 'puzzle') bindPuzzle(route.number); if (route.name === 'files') bindFiles(); document.querySelector('#noticeButton')?.addEventListener('click', () => showToast('公告详情将在公告模块接入后开放')); document.querySelector('#profileButton')?.addEventListener('click', () => showToast('当前为本地演示账户')); }
function bindFiles() { document.querySelector('#newFolderButton')?.addEventListener('click', openNewFolder); document.querySelector('#newFolderCard')?.addEventListener('click', openNewFolder); document.querySelectorAll('[data-folder]').forEach((folder) => folder.addEventListener('click', () => { state.filePath = ['全部文件', folder.querySelector('strong').textContent]; renderRoute(); showToast(`已打开文件夹：${state.filePath[1]}`); })); document.querySelector('[data-file-home]')?.addEventListener('click', () => { state.filePath = ['全部文件']; renderRoute(); }); document.querySelector('#sortFilesButton')?.addEventListener('click', (event) => { event.currentTarget.textContent = event.currentTarget.textContent === '按最近更新' ? '按名称排序' : '按最近更新'; showToast('文件排序方式已切换'); }); }
function openNewFolder() { openModal(`<p class="modal-eyebrow">FILE MANAGER</p><h2 id="modalTitle">新建文件夹</h2><p class="modal-intro">文件夹可以表示来源、年份或题集，并且可以继续嵌套。</p><label class="form-field"><span>文件夹名称</span><input id="newFolderName" type="text" placeholder="例如：2026" /></label><label class="form-field"><span>上级文件夹（可选）</span><select id="newFolderParent"><option value="">根目录</option>${state.folders.map((folder) => `<option value="${esc(folder.id)}">${esc(folder.name)}</option>`).join('')}</select></label><div class="modal-footer"><button class="button button-light modal-cancel" type="button">取消</button>${button('创建文件夹', 'createFolderButton')}</div>`); document.querySelector('#createFolderButton').addEventListener('click', async () => { const name = document.querySelector('#newFolderName').value.trim(); if (!name) { showToast('请填写文件夹名称'); return; } const parent = document.querySelector('#newFolderParent').value || null; try { if (state.api) { const data = await apiRequest('/api/folders', { method: 'POST', body: JSON.stringify({ name, parentId: parent }) }); state.folders = data.folders.map((folder) => ({ id: String(folder.id), name: folder.name, count: folder.count, parent: folder.parent })); } else { const id = `folder-${Date.now()}`; state.folders.push({ id, name, count: 0, parent }); saveState(); } closeModal(); renderRoute(); showToast(`文件夹「${name}」已创建`); } catch (error) { showToast(error.message); } }); }

document.querySelector('#searchButton').addEventListener('click', () => { const search = window.prompt('搜索题目、作者或标签'); if (search) { const match = state.puzzles.find((puzzle) => `${puzzle.title} ${puzzle.author} ${puzzle.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())); window.location.hash = match ? `#puzzle-${match.number}` : '#library'; showToast(match ? `已找到「${match.title}」` : `没有找到「${search}」`); } });
document.querySelector('#notificationButton').addEventListener('click', () => showToast('暂无新通知'));
document.querySelector('#loginButton').addEventListener('click', () => openModal(`<p class="modal-eyebrow">YOUR SPACE</p><h2>登录 PuzArchive</h2><p class="modal-intro">邮箱登录和验证码将在账户模块接入后启用。</p><label class="form-field"><span>邮箱地址</span><input type="email" placeholder="you@example.com" /></label><div class="modal-footer">${button('发送验证码', 'loginDemoButton')}</div>`));
modalBackdrop.addEventListener('click', (event) => { if (event.target === modalBackdrop || event.target.closest('.modal-close') || event.target.closest('.modal-cancel')) closeModal(); if (event.target.id === 'loginDemoButton') { closeModal(); showToast('验证码发送功能将在账户系统接入后启用'); } });
window.addEventListener('hashchange', renderRoute);
renderRoute();
bootstrapDatabase();
