import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { DatabaseSync } from 'node:sqlite';

const tempDir=fs.mkdtempSync(path.join(os.tmpdir(),'puzarchive-api-'));
const dbPath=path.join(tempDir,'legacy.sqlite');
const usersPath=path.join(tempDir,'trusted-users.json');
const members=[
  {id:'trusted-1',name:'Ada',accessCode:'test-invitation-code-ada-001'}
];
fs.writeFileSync(usersPath,JSON.stringify(members));
const legacy=new DatabaseSync(dbPath);
legacy.exec(`CREATE TABLE puzzles (id INTEGER PRIMARY KEY,number INTEGER NOT NULL UNIQUE,title TEXT NOT NULL,type TEXT NOT NULL,author TEXT NOT NULL,source TEXT NOT NULL,url TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',rules TEXT NOT NULL DEFAULT '',input_mode TEXT NOT NULL DEFAULT 'external',answer TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO puzzles(number,title,type,author,source,url,note,rules,input_mode,answer) VALUES(777,'Legacy puzzle','逻辑题','Old author','puzz.link','https://puzz.link/','','old rule','external','');`);
legacy.exec(`ALTER TABLE puzzles ADD COLUMN scope TEXT NOT NULL DEFAULT 'public';
ALTER TABLE puzzles ADD COLUMN suggested_date TEXT;
ALTER TABLE puzzles ADD COLUMN submitted_by TEXT;
INSERT INTO puzzles(number,title,type,author,source,url,note,rules,input_mode,answer,scope,suggested_date,submitted_by)
VALUES(776,'Legacy calendar puzzle','逻辑题','Old author','legacy calendar','','','old rule','external','','calendar','2024-02-29','trusted-1');
CREATE TABLE puzzle_ratings (id INTEGER PRIMARY KEY,puzzle_id INTEGER NOT NULL,user_id TEXT NOT NULL,logic INTEGER NOT NULL,intuition INTEGER NOT NULL,enjoyment INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(puzzle_id,user_id));
CREATE TABLE puzzle_completions (puzzle_id INTEGER NOT NULL,user_id TEXT NOT NULL,completed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(puzzle_id,user_id));
INSERT INTO puzzle_ratings(puzzle_id,user_id,logic,intuition,enjoyment) VALUES(2,'trusted-1',5,4,3);
INSERT INTO puzzle_completions(puzzle_id,user_id) VALUES(2,'trusted-1');`);
legacy.exec(`CREATE TABLE trusted_users (id TEXT PRIMARY KEY,name TEXT NOT NULL,access_code_hash TEXT NOT NULL DEFAULT '');
CREATE TABLE member_sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL);`);
legacy.exec(`CREATE TABLE rules (id INTEGER PRIMARY KEY,title_zh TEXT NOT NULL,title_en TEXT NOT NULL,rules_zh TEXT NOT NULL,rules_en TEXT NOT NULL,category TEXT NOT NULL,is_variant INTEGER NOT NULL,base_rule_id INTEGER REFERENCES rules(id));
INSERT INTO rules(id,title_zh,title_en,rules_zh,rules_en,category,is_variant) VALUES(42,'Legacy rule','Legacy rule','["旧中文说明"]','["Old English description"]','其它',0);`);
legacy.exec(`CREATE TABLE rule_item_revisions (rule_id INTEGER NOT NULL,item TEXT NOT NULL,revision INTEGER NOT NULL,content_json TEXT NOT NULL,changed_by_user_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(rule_id,item,revision));
INSERT INTO rule_item_revisions(rule_id,item,revision,content_json) VALUES(42,'example',1,'{"exampleUrl":""}');`);
const sha256=(value)=>createHash('sha256').update(value).digest('hex');
legacy.prepare('INSERT INTO trusted_users(id,name,access_code_hash) VALUES (?,?,?)').run('trusted-1','Old Ada',sha256('stale-ada-code-before-rotation'));
legacy.prepare('INSERT INTO trusted_users(id,name,access_code_hash) VALUES (?,?,?)').run('removed-user','Removed Member',sha256('removed-member-invite'));
legacy.prepare('INSERT INTO member_sessions(token_hash,user_id,expires_at) VALUES (?,?,?)').run(sha256('old-invitation-session'), 'trusted-1', Date.now()+60*60*1000);
legacy.close();
process.env.PUZARCHIVE_DB_PATH=dbPath;
process.env.PUZARCHIVE_USERS_PATH=usersPath;
const {createServer}=await import('../server.mjs');
const {authBootstrapComplete,bootstrapLegacyAuth,database,findSession,getRule,setRegistrationGate}=await import('../db.mjs');

function assertParticipants(actual,expected) {
  assert.ok(Array.isArray(actual));
  const byUsername=(a,b)=>String(a.username).localeCompare(String(b.username));
  assert.deepEqual([...actual].sort(byUsername),[...expected].sort(byUsername));
}

function assertReviewParticipants(review,expected={}) {
  const scores=[-2,-1,0,1,2,'veto'];
  assert.deepEqual(Object.keys(review.scoreParticipants).sort(),scores.map(String).sort());
  for (const score of scores) {
    assertParticipants(review.scoreParticipants[score],expected[score]||[]);
    assert.equal(review.scoreParticipants[score].length,score==='veto'?review.veto:review.scores[score]);
  }
  const people=scores.flatMap((score)=>review.scoreParticipants[score]);
  assert.equal(new Set(people.map((person)=>person.username)).size,people.length);
}

test('fresh database seed assigns unique delete tokens before puzzle seeding',()=>{
  const isolated=fs.mkdtempSync(path.join(os.tmpdir(),'puzarchive-fresh-db-'));
  try {
    const freshPath=path.join(isolated,'fresh.sqlite');
    const moduleUrl=new URL('../db.mjs',import.meta.url).href;
    const child=spawnSync(process.execPath,['--input-type=module','-e',`import {database} from ${JSON.stringify(moduleUrl)}; const p=database.prepare('SELECT COUNT(*) AS count,COUNT(DISTINCT delete_token) AS uniqueTokens,MIN(LENGTH(delete_token)) AS minLength FROM puzzles').get(); const r=database.prepare('SELECT COUNT(*) AS count,COUNT(DISTINCT delete_token) AS uniqueTokens,MIN(LENGTH(delete_token)) AS minLength FROM rules').get(); console.log(JSON.stringify({puzzles:p,rules:r})); database.close();`],{encoding:'utf8',env:{...process.env,PUZARCHIVE_DB_PATH:freshPath,PUZARCHIVE_USERS_PATH:path.join(isolated,'trusted-users.json')}});
    assert.equal(child.status,0,`${child.stderr}\n${child.stdout}`);
    const result=JSON.parse(child.stdout.trim().split('\n').at(-1));
    assert.deepEqual(result.puzzles,{count:8,uniqueTokens:8,minLength:36});
    assert.deepEqual(result.rules,{count:0,uniqueTokens:0,minLength:null});
  } finally { fs.rmSync(isolated,{recursive:true,force:true}); }
});

test('one-time invite migration preserves identities, invalidates old sessions, and supports username-password accounts',async(t)=>{
  assert.equal(authBootstrapComplete(),true);
  assert.equal(findSession(sha256('old-invitation-session')),null);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM puzzles WHERE number=777').get().count,1);
  assert.equal(database.prepare('SELECT calendar_year FROM puzzles WHERE number=776').get().calendar_year,2024);
  const migratedEvaluation=database.prepare('SELECT difficulty,tags_json,review_round FROM calendar_evaluations WHERE puzzle_id=(SELECT id FROM puzzles WHERE number=776) AND user_id=?').get('trusted-1');
  assert.equal(migratedEvaluation.difficulty,5);
  assert.equal(migratedEvaluation.tags_json,'[]');
  assert.equal(migratedEvaluation.review_round,1);
  const preservedRating=database.prepare('SELECT logic,intuition,enjoyment FROM puzzle_ratings WHERE puzzle_id=(SELECT id FROM puzzles WHERE number=776) AND user_id=?').get('trusted-1');
  assert.equal(preservedRating.logic,5);
  assert.equal(preservedRating.intuition,4);
  assert.equal(preservedRating.enjoyment,3);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM calendar_review_votes WHERE puzzle_id=(SELECT id FROM puzzles WHERE number=776)').get().count,0);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM user_notifications').get().count,0);
  const legacyRule=getRule(42);
  assert.ok(legacyRule.deleteToken);
  assert.equal(legacyRule.titleZh,'Legacy rule');
  assert.equal(legacyRule.exampleUrl,'');
  assert.equal(legacyRule.creator,null);
  assert.deepEqual(legacyRule.revisions,{name:1,description:1,example:1});
  assert.ok(legacyRule.quality.errors.some((error)=>error.code==='missingExample'));
  assert.deepEqual(legacyRule.quality.groups.example.revisions[0].content,{exampleUrl:'',exampleAuthor:''});
  assert.equal(database.prepare("SELECT content_json FROM rule_item_revisions WHERE rule_id=42 AND item='example' AND revision=1").get().content_json,'{"exampleUrl":""}');
  assert.equal(database.prepare('SELECT is_active FROM trusted_users WHERE id=?').get('removed-user').is_active,0);
  assert.equal(database.prepare('SELECT pending_legacy_user_id FROM registration_gate WHERE id=1').get().pending_legacy_user_id,'trusted-1');
  assert.ok(database.prepare('SELECT delete_token FROM puzzles WHERE number=777').get().delete_token);
  assert.equal(bootstrapLegacyAuth([{id:'trusted-1',name:'Ada',accessCodeHash:sha256(members[0].accessCode)}]),false);

  const server=createServer();
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  t.after(()=>new Promise((resolve)=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  async function request(url,options={},cookie='') {
    const method=options.method||'GET';
    const response=await fetch(`${base}${url}`,{...options,headers:{...(options.headers||{}),host:`127.0.0.1:${server.address().port}`,...(method!=='GET'?{origin:base}:{}),...(cookie?{cookie}:{}),...(options.body?{'content-type':'application/json'}:{})}});
    const body=await response.json().catch(()=>null);
    return {response,body,cookie:response.headers.get('set-cookie')?.split(';')[0]||cookie};
  }
  const anonymous=await request('/api/calendar/puzzles');
  assert.equal(anonymous.response.status,401);
  assert.equal((await request('/api/puzzles')).response.status,401);
  assert.equal((await request('/data/trusted-users.json')).response.status,404);
  assert.equal((await request('/db.mjs')).response.status,404);
  assert.equal((await request('/scripts/import-rules.mjs')).response.status,404);
  assert.equal((await request('/tools/prepare-rule-import.py')).response.status,404);

  const rotatedCode=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:'stale-ada-code-before-rotation',username:'Ada',password:'correct horse battery staple'})});
  assert.equal(rotatedCode.response.status,400);
  const removedCode=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:'removed-member-invite',username:'Removed',password:'correct horse battery staple'})});
  assert.equal(removedCode.response.status,400);
  const minimumPassword='testpass';
  const tooShort=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:members[0].accessCode,username:'Ada',password:minimumPassword.slice(0,-1)})});
  assert.equal(tooShort.response.status,400);
  assert.equal(tooShort.body.error,'password must be 8–128 characters and at most 512 UTF-8 bytes');
  assert.equal(database.prepare('SELECT pending_legacy_user_id FROM registration_gate WHERE id=1').get().pending_legacy_user_id,'trusted-1');
  const gateHash=database.prepare('SELECT token_hash FROM registration_gate WHERE id=1').get().token_hash;
  const legacyClaimRace=await Promise.all(['Ada','Ａda'].map((username)=>request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:members[0].accessCode,username,password:minimumPassword})})));
  assert.deepEqual(legacyClaimRace.map((result)=>result.response.status).sort(),[201,409]);
  const adaRegistration=legacyClaimRace.find((result)=>result.response.status===201);
  assert.equal(adaRegistration.body.user.id,'trusted-1');
  assert.equal(adaRegistration.body.user.name,'Ada');
  assert.equal(adaRegistration.body.user.username,'Ada');
  assert.equal(database.prepare('SELECT pending_legacy_user_id FROM registration_gate WHERE id=1').get().pending_legacy_user_id,null);
  assert.equal(database.prepare('SELECT token_hash FROM registration_gate WHERE id=1').get().token_hash,gateHash);
  assert.match(adaRegistration.response.headers.get('set-cookie'),/HttpOnly/);
  assert.match(adaRegistration.response.headers.get('set-cookie'),/SameSite=Strict/);
  const ada=adaRegistration.cookie;
  const reusableCode=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:members[0].accessCode,username:'Ada2',password:'correct horse battery staple'})});
  assert.equal(reusableCode.response.status,201);
  const wrongPassword=await request('/api/session',{method:'POST',body:JSON.stringify({username:'ada',password:'incorrect horse battery staple'})});
  assert.equal(wrongPassword.response.status,401);
  const oldLogin=await request('/api/session',{method:'POST',body:JSON.stringify({accessCode:members[0].accessCode})});
  assert.equal(oldLogin.response.status,400);
  const adaLogin=await request('/api/session',{method:'POST',body:JSON.stringify({username:'ada',password:minimumPassword})});
  assert.equal(adaLogin.response.status,200);
  assert.equal(adaLogin.body.user.id,'trusted-1');
  assert.equal(adaLogin.body.user.username,'Ada');
  const rules0=await request('/api/rules',{},ada);
  assert.deepEqual(rules0.body.rules.map((rule)=>rule.id),[42]);
  const original=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'填字',titleEn:'Fillomino',rulesZh:['每个区域包含指定数量的格子。'],rulesEn:['Each region contains its numbered number of cells.'],category:'分区',isVariant:false})},ada);
  assert.equal(original.response.status,201);
  const variant=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'奇数变体',titleEn:'Odd Variant',rulesZh:['新条款'],rulesEn:['New clause'],category:'分区',isVariant:true,baseRuleId:original.body.rule.id})},ada);
  assert.equal(variant.response.status,201);
  const invalidVariant=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'错误变体',titleEn:'Bad Variant',rulesZh:['条款'],rulesEn:['Clause'],category:'其它',isVariant:true,baseRuleId:variant.body.rule.id})},ada);
  assert.equal(invalidVariant.response.status,400);
  const draftRule=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'缺英文条款',category:'其它'})},ada);
  assert.equal(draftRule.response.status,201);
  assert.ok(draftRule.body.rule.quality.errors.some((error)=>error.code==='missingEnName'));
  assert.ok(draftRule.body.rule.quality.errors.some((error)=>error.code==='missingZhDescription'));
  assert.ok(!draftRule.body.rule.quality.errors.some((error)=>error.code==='missingEnDescription'));

  const invalidDate=await request('/api/calendar/puzzles',{method:'POST',body:JSON.stringify({title:'Calendar',author:'Ada',source:'Fill-in',inputMode:'blank',ruleId:original.body.rule.id,suggestedDate:'2025-02-29'})},ada);
  assert.equal(invalidDate.response.status,400);
  const created=await request('/api/calendar/puzzles',{method:'POST',body:JSON.stringify({title:'Calendar puzzle',author:'Ada',source:'Fill-in',note:'First entry',inputMode:'blank',answer:'four',ruleId:original.body.rule.id,suggestedDate:'2024-02-29'})},ada);
  assert.equal(created.response.status,201);
  const number=created.body.puzzle.number;
  assert.equal(created.body.puzzle.scope,'calendar');
  assertParticipants(created.body.puzzle.ratingParticipants,[]);
  assertReviewParticipants(created.body.puzzle.review);
  assertReviewParticipants(created.body.puzzle.reviewHistory[0]);
  assert.ok(created.body.puzzle.deleteToken);
  assert.equal(created.body.puzzle.rule.titleEn,'Fillomino');
  assert.deepEqual(created.body.puzzle.submittedBy,{id:'trusted-1',name:'Ada',username:'Ada'});
  assert.equal(created.body.puzzle.suggestedDate,'2024-02-29');
  const referencedRuleDelete=await request(`/api/rules/${original.body.rule.id}`,{method:'DELETE',body:JSON.stringify({deleteToken:original.body.rule.deleteToken,expectedEditVersion:original.body.rule.editVersion})},ada);
  assert.equal(referencedRuleDelete.response.status,409);
  assert.equal(referencedRuleDelete.body.reason,'referenced');
  assert.deepEqual(referencedRuleDelete.body.references,{publicPuzzles:0,calendarPuzzles:1,otherPuzzles:0,totalPuzzles:1,variants:1});
  const legacyList=await request('/api/puzzles',{},ada);
  assert.deepEqual(legacyList.body.puzzles.map((p)=>p.number),[777]);
  assertParticipants(legacyList.body.puzzles[0].ratingParticipants,[]);
  assert.equal((await request('/api/tags',{},ada)).body.tags.length,0);
  assert.equal((await request('/api/calendar/puzzles',{},ada)).body.puzzles.length,2);
  assert.equal((await request(`/api/puzzles/${number}/complete-rating`,{method:'POST',body:JSON.stringify({logic:5,intuition:4,enjoyment:5})},ada)).response.status,404);

  const linPayload=Buffer.from(JSON.stringify({inviteCode:members[0].accessCode,username:'林晓',password:'密码 another correct horse battery staple'}));
  const splitAt=linPayload.indexOf(Buffer.from('密'))+1;
  async function* fragmentedBody() {
    yield linPayload.subarray(0,splitAt);
    await new Promise((resolve)=>setTimeout(resolve,1));
    yield linPayload.subarray(splitAt);
  }
  const linResponse=await fetch(`${base}/api/register`,{method:'POST',headers:{host:`127.0.0.1:${server.address().port}`,origin:base,'content-type':'application/json'},body:fragmentedBody(),duplex:'half'});
  const linRegistration={response:linResponse,body:await linResponse.json(),cookie:linResponse.headers.get('set-cookie')?.split(';')[0]||''};
  assert.equal(linRegistration.response.status,201);
  assert.equal(linRegistration.body.user.username,'林晓');
  const lin=linRegistration.cookie;
  const beaRegistration=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:members[0].accessCode,username:'Bea',password:'another correct horse battery staple'})});
  const cyRegistration=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:members[0].accessCode,username:'Cy',password:'another correct horse battery staple'})});
  const danRegistration=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:members[0].accessCode,username:'Dan',password:'another correct horse battery staple'})});
  assert.equal(beaRegistration.response.status,201);
  assert.equal(cyRegistration.response.status,201);
  assert.equal(danRegistration.response.status,201);
  const bea=beaRegistration.cookie,cy=cyRegistration.cookie,dan=danRegistration.cookie;
  const publicIdentity=(user)=>({name:user.name,username:user.username});
  const adaPerson=publicIdentity(adaRegistration.body.user),linPerson=publicIdentity(linRegistration.body.user),
    beaPerson=publicIdentity(beaRegistration.body.user),cyPerson=publicIdentity(cyRegistration.body.user),danPerson=publicIdentity(danRegistration.body.user);
  const forbidden=await request(`/api/calendar/puzzles/${number}`,{method:'PATCH',body:JSON.stringify({suggestedDate:'2026-01-01'})},lin);
  assert.equal(forbidden.response.status,403);
  const review={difficulty:3,tags:['逻辑通顺'],vote:2,expectedReviewRound:1};
  assert.equal((await request(`/api/calendar/puzzles/${number}/complete-rating`,{method:'POST',body:JSON.stringify(review)},lin)).response.status,200);
  const rateUpdate=await request(`/api/calendar/puzzles/${number}/complete-rating`,{method:'POST',body:JSON.stringify({...review,difficulty:1,tags:['美观']})},lin);
  assert.equal(Object.hasOwn(rateUpdate.body,'puzzles'),false);
  assert.equal(rateUpdate.body.puzzle.votes,1);
  assert.deepEqual(rateUpdate.body.puzzle.ratings,[0,0,0]);
  assert.equal(rateUpdate.body.puzzle.evaluation.difficulty,1);
  assert.deepEqual(rateUpdate.body.puzzle.evaluation.tags,['美观']);
  assertParticipants(rateUpdate.body.puzzle.ratingParticipants,[linPerson]);
  assertReviewParticipants(rateUpdate.body.puzzle.review,{2:[linPerson]});
  const linCalendar=await request('/api/calendar/puzzles',{},lin);
  const adaCalendar=await request('/api/calendar/puzzles',{},ada);
  assert.equal(linCalendar.body.puzzles[0].completed,true);
  assert.equal(linCalendar.body.puzzles[0].evaluation.difficulty,1);
  assert.equal(adaCalendar.body.puzzles[0].completed,false);
  assert.equal(adaCalendar.body.puzzles[0].evaluation,null);
  assertParticipants(adaCalendar.body.puzzles[0].ratingParticipants,[linPerson]);
  assertReviewParticipants(adaCalendar.body.puzzles[0].review,{2:[linPerson]});

  const defaultYearPuzzle=await request('/api/calendar/puzzles',{method:'POST',body:JSON.stringify({title:'No date yet',source:'Fill-in',inputMode:'blank',ruleId:original.body.rule.id,submittedBy:{id:'forged'}})},ada);
  assert.equal(defaultYearPuzzle.response.status,201);
  const newCalendarNumber=defaultYearPuzzle.body.puzzle.number;
  assert.equal(defaultYearPuzzle.body.puzzle.calendarYear,2028);
  assert.equal(defaultYearPuzzle.body.puzzle.suggestedMonthDay,'');
  assert.equal(defaultYearPuzzle.body.puzzle.author,'Ada');
  assert.equal(defaultYearPuzzle.body.puzzle.submittedBy.id,'trusted-1');
  assert.equal((await request(`/api/calendar/puzzles/${newCalendarNumber}`)).response.status,401);
  assert.equal((await request('/api/calendar/leftovers')).response.status,401);
  const reviewFor=(vote,difficulty=4)=>({difficulty,tags:['逻辑通顺','美观'],vote,expectedReviewRound:1,userId:'forged-reviewer'});
  const invalidScore=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(7,7))},ada);
  assert.equal(invalidScore.response.status,400);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM calendar_evaluations WHERE puzzle_id=(SELECT id FROM puzzles WHERE number=?)').get(newCalendarNumber).count,0);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM puzzle_completions WHERE puzzle_id=(SELECT id FROM puzzles WHERE number=?)').get(newCalendarNumber).count,0);
  for (const [cookie,vote] of [[ada,2],[lin,2],[bea,1],[cy,0],[dan,-1]]) {
    const result=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(vote))},cookie);
    assert.equal(result.response.status,200);
  }
  let latest=(await request(`/api/calendar/puzzles/${newCalendarNumber}`,{},ada)).body.puzzle;
  assert.equal(latest.calendarStatus,'approved');
  assert.equal(latest.review.totalScore,4);
  assert.equal(latest.review.averageScore,0.8);
  assert.equal(latest.completed,true);
  assert.deepEqual(latest.reviewHistory.map((round)=>round.reviewRound),[1]);
  assert.equal(latest.reviewHistory[0].evaluationCount,5);
  const allEvaluators=[adaPerson,linPerson,beaPerson,cyPerson,danPerson];
  const initialVotes={2:[adaPerson,linPerson],1:[beaPerson],0:[cyPerson],[-1]:[danPerson]};
  assertParticipants(latest.ratingParticipants,allEvaluators);
  assertReviewParticipants(latest.review,initialVotes);
  assertReviewParticipants(latest.reviewHistory[0],initialVotes);
  database.prepare('UPDATE trusted_users SET is_active=0 WHERE username=?').run('Dan');
  latest=(await request(`/api/calendar/puzzles/${newCalendarNumber}`,{},ada)).body.puzzle;
  assert.equal(latest.review.scores[-1],1);
  assert.equal(Object.hasOwn(latest.review,'neutral'),false);
  assert.equal(latest.reviewHistory[0].evaluationCount,5);
  assertParticipants(latest.ratingParticipants,allEvaluators);
  assertReviewParticipants(latest.review,initialVotes);
  database.prepare('UPDATE trusted_users SET is_active=1 WHERE username=?').run('Dan');
  assert.equal(database.prepare("SELECT COUNT(*) AS count FROM calendar_review_votes WHERE user_id='forged-reviewer'").get().count,0);
  let inbox=(await request('/api/inbox?limit=50',{},ada)).body;
  assert.equal(inbox.notifications.filter((item)=>item.type==='calendar-approved'&&item.entity.id===latest.number).length,1);
  assert.equal((await request('/api/inbox?limit=50',{},lin)).body.notifications.filter((item)=>item.entity?.id===latest.number).length,0);
  const boundary=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(-2))},dan);
  assert.equal(boundary.body.puzzle.calendarStatus,'approved');
  assert.equal(boundary.body.puzzle.review.totalScore,3);
  assertReviewParticipants(boundary.body.puzzle.review,{2:[adaPerson,linPerson],1:[beaPerson],0:[cyPerson],[-2]:[danPerson]});
  const voteDown=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(-2))},cy);
  assert.equal(voteDown.response.status,200);
  assert.equal(voteDown.body.puzzle.calendarStatus,'approved');
  assert.equal(voteDown.body.puzzle.review.totalScore,1);
  assertReviewParticipants(voteDown.body.puzzle.review,{2:[adaPerson,linPerson],1:[beaPerson],[-2]:[cyPerson,danPerson]});
  const exactZero=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(0))},bea);
  assert.equal(exactZero.body.puzzle.calendarStatus,'pending');
  assert.equal(exactZero.body.puzzle.review.totalScore,0);
  const reapprove=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(2))},bea);
  assert.equal(reapprove.body.puzzle.calendarStatus,'approved');
  assert.equal(reapprove.body.puzzle.review.totalScore,2);
  assertReviewParticipants(reapprove.body.puzzle.review,{2:[adaPerson,linPerson,beaPerson],[-2]:[cyPerson,danPerson]});
  inbox=(await request('/api/inbox?limit=50',{},ada)).body;
  assert.equal(inbox.notifications.filter((item)=>item.type==='calendar-approved'&&item.entity.id===latest.number).length,2);
  const veto=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor('veto'))},dan);
  assert.equal(veto.response.status,200);
  assert.equal(veto.body.puzzle.calendarStatus,'leftover');
  const firstRoundVotes={2:[adaPerson,linPerson,beaPerson],[-2]:[cyPerson],veto:[danPerson]};
  assertReviewParticipants(veto.body.puzzle.review,firstRoundVotes);
  assertReviewParticipants(veto.body.puzzle.reviewHistory[0],firstRoundVotes);
  assert.equal((await request('/api/calendar/puzzles',{},ada)).body.puzzles.some((item)=>item.number===newCalendarNumber),false);
  assert.equal((await request('/api/calendar/leftovers',{},ada)).body.puzzles.some((item)=>item.number===newCalendarNumber),true);
  assert.equal((await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(2))},lin)).response.status,409);
  const eventsBeforeReentry=database.prepare('SELECT COUNT(*) AS count FROM calendar_review_vote_events WHERE puzzle_id=(SELECT id FROM puzzles WHERE number=?)').get(newCalendarNumber).count;
  const reentered=await request(`/api/calendar/puzzles/${newCalendarNumber}/reenter`,{method:'POST',body:JSON.stringify({expectedReviewRound:1})},cy);
  assert.equal(reentered.response.status,200);
  assert.equal(reentered.body.puzzle.reviewRound,2);
  assert.equal(reentered.body.puzzle.evaluation.difficulty,4);
  assert.equal(reentered.body.puzzle.userVote,null);
  assert.equal(reentered.body.puzzle.completed,true);
  assert.equal(reentered.body.puzzle.reviewHistory.length,2);
  assert.equal(reentered.body.puzzle.reviewHistory[0].evaluationCount,5);
  assert.equal(reentered.body.puzzle.reviewHistory[1].evaluationCount,0);
  assertParticipants(reentered.body.puzzle.ratingParticipants,allEvaluators);
  assertReviewParticipants(reentered.body.puzzle.review);
  assertReviewParticipants(reentered.body.puzzle.reviewHistory[0],firstRoundVotes);
  assertReviewParticipants(reentered.body.puzzle.reviewHistory[1]);
  const staleRound=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify(reviewFor(2))},lin);
  assert.equal(staleRound.response.status,409);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM calendar_review_vote_events WHERE puzzle_id=(SELECT id FROM puzzles WHERE number=?)').get(newCalendarNumber).count,eventsBeforeReentry);
  for (const [cookie,difficulty] of [[ada,2],[lin,4],[bea,4]]) {
    const result=await request(`/api/calendar/puzzles/${newCalendarNumber}/complete-rating`,{method:'POST',body:JSON.stringify({...reviewFor(2,difficulty),expectedReviewRound:2})},cookie);
    assert.equal(result.response.status,200);
  }
  latest=(await request(`/api/calendar/puzzles/${newCalendarNumber}`,{},ada)).body.puzzle;
  assert.equal(latest.calendarStatus,'approved');
  assert.equal(latest.evaluation.difficulty,2);
  assert.equal(latest.evaluationSummary.averageDifficulty,3.6);
  assert.equal(latest.reviewHistory[0].averageDifficulty,4);
  assert.equal(latest.reviewHistory[1].averageDifficulty,3.3);
  assert.equal(latest.votes,5);
  assertParticipants(latest.ratingParticipants,allEvaluators);
  assertReviewParticipants(latest.review,{2:[adaPerson,linPerson,beaPerson]});
  assertReviewParticipants(latest.reviewHistory[0],firstRoundVotes);
  assertReviewParticipants(latest.reviewHistory[1],{2:[adaPerson,linPerson,beaPerson]});
  const inboxItem=inbox.notifications.find((item)=>item.type==='calendar-approved'&&item.entity.id===latest.number);
  assert.ok(inboxItem);
  const readOne=await request(`/api/inbox/${inboxItem.id}/read`,{method:'POST',body:JSON.stringify({recipientUserId:'forged'})},lin);
  assert.equal(readOne.response.status,404);
  const readOwn=await request(`/api/inbox/${inboxItem.id}/read`,{method:'POST',body:'{}'},ada);
  assert.equal(readOwn.response.status,200);
  const afterRead=(await request('/api/inbox?limit=50',{},ada)).body;
  assert.ok(afterRead.notifications.some((item)=>item.id===inboxItem.id&&item.readAt));
  const readAll=await request('/api/inbox/read-all',{method:'POST',body:'{}'},ada);
  assert.equal(readAll.response.status,200);
  assert.equal(readAll.body.unreadCount,0);
  const deleteNewCalendar=await request(`/api/calendar/puzzles/${newCalendarNumber}`,{method:'DELETE',body:JSON.stringify({deleteToken:defaultYearPuzzle.body.puzzle.deleteToken})},ada);
  assert.equal(deleteNewCalendar.response.status,200);
  assert.ok((await request('/api/inbox?limit=50',{},ada)).body.notifications.some((item)=>item.id===inboxItem.id&&item.entity.id===newCalendarNumber));
  assert.equal((await request(`/api/calendar/puzzles/${number}`,{method:'PATCH',body:JSON.stringify({suggestedDate:null})},ada)).response.status,200);
  assert.equal((await request(`/api/calendar/puzzles/${number}`,{method:'DELETE',body:JSON.stringify({deleteToken:created.body.puzzle.deleteToken})})).response.status,401);
  const tagged=await request(`/api/calendar/puzzles/${number}/tags`,{method:'POST',body:JSON.stringify({tag:'delete-cleanup'})},lin);
  assert.equal(tagged.response.status,200);
  const puzzleId=database.prepare("SELECT id FROM puzzles WHERE number=? AND scope='calendar'").get(number).id;
  database.prepare('INSERT INTO collection_puzzles(collection_id,puzzle_id,position) VALUES((SELECT id FROM collections ORDER BY id LIMIT 1),?,99)').run(puzzleId);
  const deniedDelete=await request(`/api/calendar/puzzles/${number}`,{method:'DELETE',body:JSON.stringify({deleteToken:created.body.puzzle.deleteToken})},lin);
  assert.equal(deniedDelete.response.status,403);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM puzzles WHERE id=?').get(puzzleId).count,1);
  const deleted=await request(`/api/calendar/puzzles/${number}`,{method:'DELETE',body:JSON.stringify({deleteToken:created.body.puzzle.deleteToken})},ada);
  assert.equal(deleted.response.status,200);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM puzzles WHERE id=?').get(puzzleId).count,0);
  for (const table of ['puzzle_ratings','puzzle_completions','puzzle_tags','collection_puzzles']) assert.equal(database.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE puzzle_id=?`).get(puzzleId).count,0,table);
  const replacement=await request('/api/calendar/puzzles',{method:'POST',body:JSON.stringify({title:'Replacement calendar puzzle',author:'Ada',source:'Fill-in',inputMode:'blank',ruleId:original.body.rule.id,suggestedDate:null})},ada);
  assert.equal(replacement.response.status,201);
  assert.ok(replacement.body.puzzle.number>number);
  assert.notEqual(replacement.body.puzzle.deleteToken,created.body.puzzle.deleteToken);
  const stalePuzzleDelete=await request(`/api/calendar/puzzles/${number}`,{method:'DELETE',body:JSON.stringify({deleteToken:created.body.puzzle.deleteToken})},ada);
  assert.equal(stalePuzzleDelete.response.status,404);
  assert.equal((await request(`/api/calendar/puzzles/${number}/complete-rating`,{method:'POST',body:JSON.stringify({logic:1,intuition:1,enjoyment:1})},ada)).response.status,404);
  assert.equal((await request(`/api/calendar/puzzles/${number}`,{method:'PATCH',body:JSON.stringify({suggestedDate:'2026-01-01'})},ada)).response.status,404);
  assert.equal((await request(`/api/calendar/puzzles/${replacement.body.puzzle.number}`,{method:'DELETE',body:JSON.stringify({deleteToken:replacement.body.puzzle.deleteToken})},ada)).response.status,200);
  const publicReference=await request('/api/puzzles',{method:'POST',body:JSON.stringify({title:'Legacy public reference',author:'Ada',source:'fixture',inputMode:'blank',ruleId:original.body.rule.id,answer:'x'})},ada);
  assert.equal(publicReference.response.status,201);
  const publicNumber=publicReference.body.puzzles.find((puzzle)=>puzzle.title==='Legacy public reference').number;
  const publicRating={logic:5,intuition:4,enjoyment:3};
  for (const cookie of [ada,lin]) {
    const rated=await request(`/api/puzzles/${publicNumber}/complete-rating`,{method:'POST',body:JSON.stringify(publicRating)},cookie);
    assert.equal(rated.response.status,200);
  }
  const publicUpdated=await request(`/api/puzzles/${publicNumber}/complete-rating`,{method:'POST',body:JSON.stringify({...publicRating,logic:1})},ada);
  assert.equal(publicUpdated.response.status,200);
  const publicPuzzle=publicUpdated.body.puzzles.find((puzzle)=>puzzle.number===publicNumber);
  assert.equal(publicPuzzle.votes,2);
  assert.deepEqual(publicPuzzle.ratings,[3,4,3]);
  assertParticipants(publicPuzzle.ratingParticipants,[adaPerson,linPerson]);
  const publicObserver=(await request('/api/puzzles',{},bea)).body.puzzles.find((puzzle)=>puzzle.number===publicNumber);
  assert.equal(publicObserver.completed,false);
  assertParticipants(publicObserver.ratingParticipants,[adaPerson,linPerson]);
  const publicPuzzleId=database.prepare('SELECT id FROM puzzles WHERE number=?').get(publicNumber).id;
  const addLegacyRating=database.prepare('INSERT INTO puzzle_ratings(puzzle_id,user_id,logic,intuition,enjoyment) VALUES(?,?,3,3,3)');
  addLegacyRating.run(publicPuzzleId,'removed-user');
  addLegacyRating.run(publicPuzzleId,'unknown-past-reviewer');
  const withLegacyRatings=(await request('/api/puzzles',{},bea)).body.puzzles.find((puzzle)=>puzzle.number===publicNumber);
  assert.equal(withLegacyRatings.votes,4);
  assertParticipants(withLegacyRatings.ratingParticipants,[adaPerson,linPerson,{name:'Removed Member',username:null},{name:'未知用户',username:null}]);
  const legacyCalendarId=database.prepare('SELECT id FROM puzzles WHERE number=776').get().id;
  database.prepare('INSERT INTO calendar_evaluations(puzzle_id,user_id,review_round,difficulty,tags_json) VALUES(?,?,1,3,?)').run(legacyCalendarId,'unknown-past-reviewer','[]');
  database.prepare('INSERT INTO calendar_review_votes(puzzle_id,user_id,review_round,vote) VALUES(?,?,1,?)').run(legacyCalendarId,'unknown-past-reviewer','oppose');
  const legacyParticipants=(await request('/api/calendar/puzzles/776',{},ada)).body.puzzle;
  assert.equal(legacyParticipants.votes,2);
  assertParticipants(legacyParticipants.ratingParticipants,[adaPerson,{name:'未知用户',username:null}]);
  assertReviewParticipants(legacyParticipants.review,{[-2]:[{name:'未知用户',username:null}]});
  assertReviewParticipants(legacyParticipants.reviewHistory[0],{[-2]:[{name:'未知用户',username:null}]});
  const publicReferenceDelete=await request(`/api/rules/${original.body.rule.id}`,{method:'DELETE',body:JSON.stringify({deleteToken:original.body.rule.deleteToken,expectedEditVersion:original.body.rule.editVersion})},ada);
  assert.equal(publicReferenceDelete.response.status,409);
  assert.deepEqual(publicReferenceDelete.body.references,{publicPuzzles:1,calendarPuzzles:0,otherPuzzles:0,totalPuzzles:1,variants:1});
  const futureScopeRule=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'未知范围引用',rulesZh:['中文规则'],category:'其它'})},ada);
  assert.equal(futureScopeRule.response.status,201);
  database.prepare(`INSERT INTO puzzles(number,title,type,author,source,scope,rule_id,delete_token)
    VALUES((SELECT COALESCE(MAX(number),0)+1 FROM puzzles),'Future scope reference','其它','Fixture','fixture','future-scope',?,?)`).run(futureScopeRule.body.rule.id,'future-scope-delete-token');
  const insertedFuture=database.prepare("SELECT id,number FROM puzzles WHERE title='Future scope reference'").get();
  database.prepare("UPDATE entity_id_sequences SET next_id=MAX(next_id,?) WHERE name='puzzles'").run(insertedFuture.id+1);
  database.prepare("UPDATE entity_id_sequences SET next_id=MAX(next_id,?) WHERE name='puzzle-numbers'").run(insertedFuture.number+1);
  const futureScopeDelete=await request(`/api/rules/${futureScopeRule.body.rule.id}`,{method:'DELETE',body:JSON.stringify({deleteToken:futureScopeRule.body.rule.deleteToken,expectedEditVersion:futureScopeRule.body.rule.editVersion})},ada);
  assert.equal(futureScopeDelete.response.status,409);
  assert.deepEqual(futureScopeDelete.body.references,{publicPuzzles:0,calendarPuzzles:0,otherPuzzles:1,totalPuzzles:1,variants:0});
  assert.equal((await request('/api/collections',{},ada)).body.collections.length,2);
  const unauthLogout=await request('/api/session',{method:'DELETE'});
  assert.equal(unauthLogout.response.status,200);
  assert.equal((await request('/api/session',{},ada)).body.user.id,'trusted-1');
  const logout=await request('/api/session',{method:'DELETE'},ada);
  assert.equal(logout.body.user,null);
  assert.equal((await request('/api/session',{},logout.cookie)).body.user,null);
});

test('shared registration code is reusable and concurrent usernames remain unique',async(t)=>{
  const server=createServer();
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  t.after(()=>new Promise((resolve)=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  async function request(url,options={}) {
    return fetch(`${base}${url}`,{...options,headers:{host:`127.0.0.1:${server.address().port}`,origin:base,...(options.headers||{}),...(options.method&&options.method!=='GET'?{origin:base}:{})}});
  }
  const gateCode='shared-registration-gate-race-code';
  setRegistrationGate(sha256(gateCode));
  const distinctAccounts=await Promise.all([1,2].map((suffix)=>request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:gateCode,username:`Puzzle${suffix}`,password:'enough password words for test'})})));
  assert.deepEqual(distinctAccounts.map((response)=>response.status).sort(),[201,201]);
  const sameUsername=await Promise.all(['Same_User','same_user'].map((username)=>request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:gateCode,username,password:'enough password words for test'})})));
  assert.deepEqual(sameUsername.map((response)=>response.status).sort(),[201,409]);
  assert.equal(database.prepare('SELECT COUNT(*) AS count FROM trusted_users WHERE username_key=?').get('same_user').count,1);
  assert.equal(database.prepare('SELECT token_hash FROM registration_gate WHERE id=1').get().token_hash,sha256(gateCode));
  assert.equal(bootstrapLegacyAuth([{id:'trusted-1',name:'Ada',accessCodeHash:sha256(members[0].accessCode)}]),false);
  const afterRestart=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:gateCode,username:'AfterRestart',password:'enough password words for test'})});
  assert.equal(afterRestart.status,201);
  assert.equal(database.prepare('SELECT token_hash FROM registration_gate WHERE id=1').get().token_hash,sha256(gateCode));
  const restarted=spawnSync(process.execPath,['--input-type=module','-e',`import {DatabaseSync} from 'node:sqlite'; const d=new DatabaseSync(${JSON.stringify(dbPath)},{readOnly:true}); console.log(d.prepare('SELECT token_hash FROM registration_gate WHERE id=1').get().token_hash); d.close();`],{encoding:'utf8'});
  assert.equal(restarted.status,0,restarted.stderr);
  assert.equal(restarted.stdout.trim(),sha256(gateCode));
});

test('rule drafts, independent three-person audits, sticky rejection, and revision CAS work',async(t)=>{
  const server=createServer();
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  t.after(()=>new Promise((resolve)=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  async function request(url,options={},cookie='') {
    const headers={host:`127.0.0.1:${server.address().port}`,...(options.headers||{})};
    if (options.method&&options.method!=='GET') headers.origin=base;
    if (options.body) headers['content-type']='application/json';
    if (cookie) headers.cookie=cookie;
    const response=await fetch(`${base}${url}`,{...options,headers});
    const body=await response.json().catch(()=>null);
    return {response,body,cookie:response.headers.get('set-cookie')?.split(';')[0]||cookie};
  }
  const gateCode='shared-rule-review-gate-code';
  setRegistrationGate(sha256(gateCode));
  const reviewers=[];
  for (let index=1;index<=4;index++) {
    const registration=await request('/api/register',{method:'POST',body:JSON.stringify({inviteCode:gateCode,username:`ReviewUser${index}`,password:'reviewer account password long'})});
    assert.equal(registration.response.status,201);
    reviewers.push({user:registration.body.user,cookie:registration.cookie});
  }
  const owner=reviewers[0].cookie;
  const noName=await request('/api/rules',{method:'POST',body:JSON.stringify({category:'其它'})},owner);
  assert.equal(noName.response.status,400);
  const noCategory=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'只有中文名'})},owner);
  assert.equal(noCategory.response.status,400);
  for (const exampleUrl of ['javascript:alert(1)','https://penpa-edit.com/','https://penpa-edit.com.evil.example/?m=edit&p=1','https://user:pass@penpa-edit.com/?m=edit&p=1','https://penpa-edit.com:8443/?m=edit&p=1','https://puzz.link/p?slither/6/6/abc']) {
    const invalid=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'名称',category:'其它',exampleUrl})},owner);
    assert.equal(invalid.response.status,400,exampleUrl);
  }
  const oversizedExampleAuthor=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'作者名长度校验',category:'其它',exampleAuthor:'a'.repeat(201)})},owner);
  assert.equal(oversizedExampleAuthor.response.status,400);
  const overlongExampleUrl=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'例题链接长度校验',category:'其它',exampleUrl:`https://swaroopg92.github.io/penpa-edit/#m=edit&p=${'x'.repeat(4100)}`})},owner);
  assert.equal(overlongExampleUrl.response.status,400);
  const draft=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'中文规则名',rulesZh:['中文草稿说明'],rulesEn:[],category:'其它'})},owner);
  assert.equal(draft.response.status,201);
  assert.deepEqual(new Set(draft.body.rule.quality.errors.map((error)=>error.code)),new Set(['missingEnName','missingExample']));
  assert.equal(draft.body.rule.quality.groups.name.status,'incomplete');
  assert.deepEqual(new Set(draft.body.rule.quality.warnings.map((warning)=>warning.item)),new Set(['name','description','example']));
  const draftApprove=await request(`/api/rules/${draft.body.rule.id}/audits`,{method:'POST',body:JSON.stringify({item:'name',decision:'approve',revision:1})},reviewers[1].cookie);
  assert.equal(draftApprove.response.status,400);
  const draftReject=await request(`/api/rules/${draft.body.rule.id}/audits`,{method:'POST',body:JSON.stringify({item:'name',decision:'reject',revision:1})},reviewers[1].cookie);
  assert.equal(draftReject.response.status,200);
  assert.equal(Object.hasOwn(draftReject.body,'rules'),false);
  assert.equal(draftReject.body.rule.quality.groups.name.status,'rejected');
  assert.equal(draftReject.body.rule.quality.groups.name.rejectionSuggestion,'');
  assert.ok(draftReject.body.rule.quality.errors.some((error)=>error.code==='auditRejected'&&error.item==='name'));
  assert.equal(draftReject.body.rule.creator.id,reviewers[0].user.id);
  const draftRejectInbox=await request('/api/inbox?limit=50',{},reviewers[0].cookie);
  assert.equal(draftRejectInbox.body.notifications.filter((item)=>item.type==='rule-rejected'&&item.entity.id===draft.body.rule.id).length,1);
  await request(`/api/rules/${draft.body.rule.id}/audits`,{method:'POST',body:JSON.stringify({item:'name',decision:'reject',revision:1})},reviewers[1].cookie);
  assert.equal((await request('/api/inbox?limit=50',{},reviewers[0].cookie)).body.notifications.filter((item)=>item.type==='rule-rejected'&&item.entity.id===draft.body.rule.id).length,1);
  const secondReject=await request(`/api/rules/${draft.body.rule.id}/audits`,{method:'POST',body:JSON.stringify({item:'name',decision:'reject',revision:1,suggestion:'名称仍需更清楚'})},reviewers[2].cookie);
  assert.equal(secondReject.response.status,200);
  assert.equal((await request('/api/inbox?limit=50',{},reviewers[0].cookie)).body.notifications.filter((item)=>item.type==='rule-rejected'&&item.entity.id===draft.body.rule.id).length,2);

  const longPenpaExampleUrl=`https://swaroopg92.github.io/penpa-edit/#m=edit&p=${'x'.repeat(3300)}`;
  const complete=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'规则名称',titleEn:'Rule name',rulesZh:['中文规则说明'],rulesEn:['English rule description','second independent clause'],exampleUrl:longPenpaExampleUrl,exampleAuthor:'Puzzle author',category:'其它'})},owner);
  assert.equal(complete.response.status,201);
  assert.equal(complete.body.rule.exampleUrl,longPenpaExampleUrl);
  const id=complete.body.rule.id;
  assert.deepEqual(complete.body.rule.revisions,{name:1,description:1,example:1});
  assert.equal(complete.body.rule.editVersion,1);
  const audit=async(account,item,decision,revision,suggestion)=>request(`/api/rules/${id}/audits`,{method:'POST',body:JSON.stringify({item,decision,revision,...(suggestion===undefined?{}:{suggestion})})},account.cookie);
  assert.equal((await audit(reviewers[0],'name','approve',1)).response.status,200);
  const duplicateApproval=await audit(reviewers[0],'name','approve',1);
  assert.equal(duplicateApproval.body.rule.quality.groups.name.approvalCount,1);
  assert.equal(duplicateApproval.body.rule.quality.groups.name.history.length,1);
  assert.equal((await audit(reviewers[1],'name','approve',1)).body.rule.quality.groups.name.approvalCount,2);
  const rejected=await audit(reviewers[0],'name','reject',1,'请修正中文名称');
  assert.equal(rejected.response.status,200);
  assert.equal(rejected.body.rule.quality.groups.name.status,'rejected');
  assert.equal(rejected.body.rule.quality.groups.name.approvalCount,1);
  assert.equal(rejected.body.rule.quality.groups.name.history.length,3);
  assert.equal((await audit(reviewers[2],'name','approve',1)).response.status,409);
  const current=rejected.body.rule;
  const expectedRevisions={...current.revisions};
  const noOp=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({titleZh:' 规则名称 ',expectedEditVersion:current.editVersion,expectedRevisions})},owner);
  assert.equal(noOp.response.status,200);
  assert.equal(noOp.body.rule.quality.groups.name.status,'rejected');
  assert.equal(noOp.body.rule.editVersion,current.editVersion);
  const edit=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({titleZh:'规则名称修订',expectedEditVersion:current.editVersion,expectedRevisions})},owner);
  assert.equal(edit.response.status,200);
  assert.deepEqual(edit.body.rule.revisions,{name:2,description:1,example:1});
  assert.equal(edit.body.rule.quality.groups.name.status,'pending');
  assert.equal(edit.body.rule.quality.groups.description.status,'pending');
  assert.equal(edit.body.rule.quality.groups.example.status,'pending');
  assert.equal(edit.body.rule.quality.groups.name.history.length,3);
  assert.deepEqual(edit.body.rule.quality.groups.name.revisions.map((revision)=>revision.revision),[1,2]);
  assert.equal((await audit(reviewers[1],'name','approve',1)).response.status,409);
  for (const account of reviewers.slice(1,4)) assert.equal((await audit(account,'name','approve',2)).response.status,200);
  const named=await request(`/api/rules/${id}`,{},owner);
  assert.equal(named.body.rule.quality.groups.name.approvalCount,3);
  assert.equal(named.body.rule.quality.groups.name.status,'approved');

  for (const account of reviewers.slice(0,3)) assert.equal((await audit(account,'description','approve',1)).response.status,200);
  for (const account of reviewers.slice(0,3)) assert.equal((await audit(account,'example','approve',1)).response.status,200);
  const fullyApproved=await request(`/api/rules/${id}`,{},owner);
  assert.deepEqual(fullyApproved.body.rule.quality.warnings,[]);
  assert.equal(fullyApproved.body.rule.quality.groups.description.approvalCount,3);
  assert.equal(fullyApproved.body.rule.quality.groups.example.approvalCount,3);
  assert.equal(fullyApproved.body.rule.exampleAuthor,'Puzzle author');
  assert.equal(fullyApproved.body.rule.creator.id,reviewers[0].user.id);
  assert.equal((await request('/api/inbox?limit=50',{},reviewers[0].cookie)).body.notifications.filter((item)=>item.type==='rule-approved'&&item.entity.id===id).length,1);
  const authorEdit=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({exampleAuthor:'Another puzzle author',expectedEditVersion:fullyApproved.body.rule.editVersion,expectedRevisions:fullyApproved.body.rule.revisions})},owner);
  assert.equal(authorEdit.response.status,200);
  assert.deepEqual(authorEdit.body.rule.revisions,{name:2,description:1,example:2});
  assert.equal(authorEdit.body.rule.exampleUrl,fullyApproved.body.rule.exampleUrl);
  assert.equal(authorEdit.body.rule.quality.groups.example.status,'pending');
  assert.equal(authorEdit.body.rule.quality.groups.name.status,'approved');
  assert.equal(authorEdit.body.rule.quality.groups.description.status,'approved');
  assert.deepEqual(authorEdit.body.rule.quality.groups.example.revisions[1].content,{exampleUrl:fullyApproved.body.rule.exampleUrl,exampleAuthor:'Another puzzle author'});
  const categoryEdit=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({category:'填数',expectedEditVersion:fullyApproved.body.rule.editVersion,expectedRevisions:fullyApproved.body.rule.revisions})},owner);
  assert.equal(categoryEdit.response.status,409);
  const categoryAfterAuthor=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({category:'填数',expectedEditVersion:authorEdit.body.rule.editVersion,expectedRevisions:authorEdit.body.rule.revisions})},owner);
  assert.equal(categoryAfterAuthor.response.status,200);
  assert.deepEqual(categoryAfterAuthor.body.rule.revisions,authorEdit.body.rule.revisions);
  assert.equal(categoryAfterAuthor.body.rule.editVersion,authorEdit.body.rule.editVersion+1);
  assert.equal(categoryAfterAuthor.body.rule.quality.groups.description.status,'approved');
  const staleCategory=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({category:'路径',expectedEditVersion:authorEdit.body.rule.editVersion,expectedRevisions:authorEdit.body.rule.revisions})},owner);
  assert.equal(staleCategory.response.status,409);
  const exampleEdit=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({exampleUrl:'https://penpa-edit.com/?m=edit&p=updated',expectedEditVersion:categoryAfterAuthor.body.rule.editVersion,expectedRevisions:categoryAfterAuthor.body.rule.revisions})},owner);
  assert.equal(exampleEdit.response.status,200);
  assert.deepEqual(exampleEdit.body.rule.revisions,{name:2,description:1,example:3});
  assert.equal(exampleEdit.body.rule.quality.groups.example.status,'pending');
  assert.equal(exampleEdit.body.rule.quality.groups.example.history.length,3);
  assert.equal(exampleEdit.body.rule.quality.groups.name.status,'approved');
  assert.equal(exampleEdit.body.rule.quality.groups.description.status,'approved');
  const clearExample=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({exampleUrl:null,expectedEditVersion:exampleEdit.body.rule.editVersion,expectedRevisions:exampleEdit.body.rule.revisions})},owner);
  assert.equal(clearExample.response.status,200);
  assert.deepEqual(clearExample.body.rule.revisions,{name:2,description:1,example:4});
  assert.equal(clearExample.body.rule.exampleUrl,'');
  assert.equal(clearExample.body.rule.quality.groups.example.status,'incomplete');
  assert.ok(clearExample.body.rule.quality.errors.some((error)=>error.code==='missingExample'));
  assert.equal(clearExample.body.rule.quality.groups.example.history.length,3);

  const missingBase=await request('/api/rules',{method:'POST',body:JSON.stringify({titleEn:'Variant draft',category:'路径',isVariant:true,rulesZh:['说明'],rulesEn:['Description']})},owner);
  assert.equal(missingBase.response.status,201);
  assert.ok(missingBase.body.rule.quality.errors.some((error)=>error.code==='missingVariantBase'));
  const invalidBase=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'Invalid variant',category:'路径',isVariant:true,baseRuleId:999999})},owner);
  assert.equal(invalidBase.response.status,400);
  const dependent=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'Dependent variant',category:'路径',isVariant:true,baseRuleId:id})},owner);
  assert.equal(dependent.response.status,201);
  const selfBase=await request(`/api/rules/${dependent.body.rule.id}`,{method:'PATCH',body:JSON.stringify({baseRuleId:dependent.body.rule.id,expectedEditVersion:dependent.body.rule.editVersion,expectedRevisions:dependent.body.rule.revisions})},owner);
  assert.equal(selfBase.response.status,400);
  const breakBase=await request(`/api/rules/${id}`,{method:'PATCH',body:JSON.stringify({isVariant:true,baseRuleId:42,expectedEditVersion:clearExample.body.rule.editVersion,expectedRevisions:clearExample.body.rule.revisions})},owner);
  assert.equal(breakBase.response.status,400);
  const changedVariantBase=await request(`/api/rules/${dependent.body.rule.id}`,{method:'PATCH',body:JSON.stringify({baseRuleId:42,expectedEditVersion:dependent.body.rule.editVersion,expectedRevisions:dependent.body.rule.revisions})},owner);
  assert.equal(changedVariantBase.response.status,200);
  assert.deepEqual(changedVariantBase.body.rule.revisions,{name:1,description:2,example:1});

  const optionalEnglish=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'英文说明可选',titleEn:'English optional',rulesZh:['中文说明'],rulesEn:[],exampleUrl:'https://penpa-edit.com/?m=edit&p=english-optional',category:'其它'})},owner);
  assert.equal(optionalEnglish.response.status,201);
  assert.ok(!optionalEnglish.body.rule.quality.errors.some((error)=>error.code==='missingEnDescription'));
  assert.ok(optionalEnglish.body.rule.quality.warnings.some((warning)=>warning.item==='description'));
  for (const account of reviewers.slice(0,3)) {
    const reviewed=await request(`/api/rules/${optionalEnglish.body.rule.id}/audits`,{method:'POST',body:JSON.stringify({item:'description',decision:'approve',revision:1})},account.cookie);
    assert.equal(reviewed.response.status,200);
  }
  const approvedWithoutEnglish=await request(`/api/rules/${optionalEnglish.body.rule.id}`,{},owner);
  assert.equal(approvedWithoutEnglish.body.rule.quality.groups.description.status,'approved');
  assert.ok(!approvedWithoutEnglish.body.rule.quality.warnings.some((warning)=>warning.item==='description'));
  const englishAdded=await request(`/api/rules/${optionalEnglish.body.rule.id}`,{method:'PATCH',body:JSON.stringify({rulesEn:['English translation'],expectedEditVersion:approvedWithoutEnglish.body.rule.editVersion,expectedRevisions:approvedWithoutEnglish.body.rule.revisions})},owner);
  assert.equal(englishAdded.response.status,200);
  assert.equal(englishAdded.body.rule.revisions.description,2);
  assert.equal(englishAdded.body.rule.quality.groups.description.status,'pending');
  const optionalId=optionalEnglish.body.rule.id, optionalToken=optionalEnglish.body.rule.deleteToken;
  assert.ok(optionalToken);
  const anonymousDelete=await request(`/api/rules/${optionalId}`,{method:'DELETE',body:JSON.stringify({deleteToken:optionalToken,expectedEditVersion:englishAdded.body.rule.editVersion})});
  assert.equal(anonymousDelete.response.status,401);
  const csrfDelete=await fetch(`${base}/api/rules/${optionalId}`,{method:'DELETE',headers:{host:`127.0.0.1:${server.address().port}`,'content-type':'application/json',cookie:owner},body:JSON.stringify({deleteToken:optionalToken,expectedEditVersion:englishAdded.body.rule.editVersion})});
  assert.equal(csrfDelete.status,403);
  const staleDelete=await request(`/api/rules/${optionalId}`,{method:'DELETE',body:JSON.stringify({deleteToken:optionalToken,expectedEditVersion:englishAdded.body.rule.editVersion+1})},owner);
  assert.equal(staleDelete.response.status,409);
  assert.equal(staleDelete.body.reason,'stale');
  const deletedOptional=await request(`/api/rules/${optionalId}`,{method:'DELETE',body:JSON.stringify({deleteToken:optionalToken,expectedEditVersion:englishAdded.body.rule.editVersion})},owner);
  assert.equal(deletedOptional.response.status,200);
  for (const table of ['rules','rule_item_revisions','rule_item_votes','rule_item_audit_events']) assert.equal(database.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE ${table==='rules'?'id':'rule_id'}=?`).get(optionalId).count,0,table);
  const replacementRule=await request('/api/rules',{method:'POST',body:JSON.stringify({titleZh:'复用编号替代规则',rulesZh:['有效说明'],category:'其它'})},owner);
  assert.equal(replacementRule.response.status,201);
  assert.ok(replacementRule.body.rule.id>optionalId);
  assert.notEqual(replacementRule.body.rule.deleteToken,optionalToken);
  const staleRuleDelete=await request(`/api/rules/${optionalId}`,{method:'DELETE',body:JSON.stringify({deleteToken:optionalToken,expectedEditVersion:englishAdded.body.rule.editVersion})},owner);
  assert.equal(staleRuleDelete.response.status,404);
  assert.equal((await request(`/api/rules/${optionalId}`,{},owner)).response.status,404);
  assert.equal((await request(`/api/rules/${optionalId}`,{method:'PATCH',body:JSON.stringify({titleZh:'stale',expectedEditVersion:englishAdded.body.rule.editVersion,expectedRevisions:englishAdded.body.rule.revisions})},owner)).response.status,404);
  assert.equal((await request(`/api/rules/${optionalId}/audits`,{method:'POST',body:JSON.stringify({item:'name',decision:'approve',revision:1})},owner)).response.status,404);
  assert.equal((await request(`/api/rules/${replacementRule.body.rule.id}`,{method:'DELETE',body:JSON.stringify({deleteToken:replacementRule.body.rule.deleteToken,expectedEditVersion:replacementRule.body.rule.editVersion})},owner)).response.status,200);
});

test('forwarded headers are ignored by default and accepted only in trusted loopback proxy mode',async(t)=>{
  const server=createServer();
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  t.after(()=>new Promise((resolve)=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const headers={host:`127.0.0.1:${server.address().port}`,origin:base,'content-type':'application/json','x-forwarded-proto':'https','x-real-ip':'203.0.113.20'};
  const directCode='direct-proxy-mode-invite-code';
  setRegistrationGate(sha256(directCode));
  const directPayload={inviteCode:directCode,username:'DirectUser',password:'direct user password long'};
  const spoofed=await fetch(`${base}/api/register`,{method:'POST',headers,body:JSON.stringify(directPayload)});
  assert.equal(spoofed.status,201);
  assert.doesNotMatch(spoofed.headers.get('set-cookie'),/; Secure(?:;|$)/);
  const wrongScheme=await fetch(`${base}/api/register`,{method:'POST',headers:{...headers,origin:base.replace('http:','https:')},body:JSON.stringify(directPayload)});
  assert.equal(wrongScheme.status,403);

  const proxyServer=createServer({trustLoopbackProxy:true});
  await new Promise((resolve,reject)=>{proxyServer.once('error',reject);proxyServer.listen(0,'127.0.0.1',resolve);});
  t.after(()=>new Promise((resolve)=>proxyServer.close(resolve)));
  const proxyBase=`http://127.0.0.1:${proxyServer.address().port}`;
  const proxyCode='trusted-proxy-mode-invite-code';
  setRegistrationGate(sha256(proxyCode));
  const proxyPayload={inviteCode:proxyCode,username:'ProxyUser',password:'proxy user password long'};
  const proxyHeaders={...headers,host:`127.0.0.1:${proxyServer.address().port}`,origin:proxyBase.replace('http:','https:')};
  const proxied=await fetch(`${proxyBase}/api/register`,{method:'POST',headers:proxyHeaders,body:JSON.stringify(proxyPayload)});
  assert.equal(proxied.status,201);
  assert.match(proxied.headers.get('set-cookie'),/; Secure(?:;|$)/);
  const proxyCookie=proxied.headers.get('set-cookie').split(';')[0];
  const secureLogout=await fetch(`${proxyBase}/api/session`,{method:'DELETE',headers:{...proxyHeaders,cookie:proxyCookie}});
  assert.match(secureLogout.headers.get('set-cookie'),/; Secure(?:;|$)/);
  const invalidForwardedIp=await fetch(`${proxyBase}/api/session`,{method:'POST',headers:{...proxyHeaders,'x-real-ip':'203.0.113.20, 198.51.100.4'},body:JSON.stringify({username:'proxyuser',password:'proxy user password long'})});
  assert.equal(invalidForwardedIp.status,403);

  const addressA={...proxyHeaders,'x-real-ip':'198.51.100.31'};
  for (let attempt=0;attempt<12;attempt++) {
    const failed=await fetch(`${proxyBase}/api/session`,{method:'POST',headers:addressA,body:JSON.stringify({username:'UnknownUser',password:'wrong password that is long'})});
    assert.equal(failed.status,401);
  }
  assert.equal((await fetch(`${proxyBase}/api/session`,{method:'POST',headers:addressA,body:JSON.stringify({username:'UnknownUser',password:'wrong password that is long'})})).status,429);
  const addressB={...addressA,'x-real-ip':'198.51.100.32'};
  assert.equal((await fetch(`${proxyBase}/api/session`,{method:'POST',headers:addressB,body:JSON.stringify({username:'proxyuser',password:'proxy user password long'})})).status,200);
});
