server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 444;
}

server {
    listen 80;
    listen [::]:80;
    server_name 62.234.13.10;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/puzarchive-acme;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
